### ISSUE TITLE
Colorspace conversions

### ISSUE THREAD

**Issue by SLS8** [dlemstra/GraphicsMagick.NET#3]
Hi
A few years ago I was asking how to do colorspace conversions in GraphicsMagick.NET in the codeplex forum https://graphicsmagick.codeplex.com/discussions/644950

I've tested the same code with the most recent version 1.3.25.0 and it still doesn't do anything. The same code works fine using the Magick.NET library instead and in the command line version of graphicsmagick. 
Thanks.

**Comment by dlemstra** [comment]
Are you using the same code in Magick.NET and GraphicsMagick.NET? And did you add setting the `RenderingIntent` to your code? Can you also add your test image and color profiles to this issue so I can reproduce it? Did you test it on the command line with the latest version of GM?

**Comment by SLS8** [comment]
Yes, the same code in both.
Adding RenderingIntent to Perceptual doesn't fix the output in GM.net
The command line version of both GM  and IM is working fine, latest gm.exe version 1.3.25 included.

For a test use a public domain image like [this ](https://pixabay.com/en/surfer-wave-sunset-the-indian-ocean-2212948/) and any b/w profile from [here](https://people.csail.mit.edu/ericchan/dp/Epson3800/abwprofiles.html) like "3800 AIS ABW 1440.icc". the output should be black and white, however on GM.net it doesn't do anything.

Thanks!

![2017-04-24_171755](https://cloud.githubusercontent.com/assets/27860241/25341593/fe78c086-2911-11e7-9107-e3d90377fa20.jpg)


            GraphicsMagick.MagickImage input = new GraphicsMagick.MagickImage(@"v:\surfer.jpg");
            GraphicsMagick.ColorProfile imp_srgb = new GraphicsMagick.ColorProfile(@"W:\sRGB.icc");
            GraphicsMagick.ColorProfile imp_bw = new GraphicsMagick.ColorProfile(@"W:\3800AISABW1440.icc");

            ImageMagick.MagickImage input2 = new ImageMagick.MagickImage(@"v:\surfer.jpg");
            ImageMagick.ColorProfile imp_srgb2 = new ImageMagick.ColorProfile(@"W:\sRGB.icc");
            ImageMagick.ColorProfile imp_bw2 = new ImageMagick.ColorProfile(@"W:\3800AISABW1440.icc");

            input.Strip();
            input.RenderingIntent = GraphicsMagick.RenderingIntent.Perceptual;
            input.AddProfile(imp_srgb);
            input.AddProfile(imp_bw);

            input2.Strip();
            input2.RenderingIntent = ImageMagick.RenderingIntent.Perceptual;
            input2.AddProfile(imp_srgb2);
            input2.AddProfile(imp_bw2);

            pictureboxGM.Image = input.ToBitmap();
            pictureboxIM.Image = input2.ToBitmap();

**Comment by dlemstra** [comment]
Can you give it another try with GraphicsMagick.NET 1.3.25.1? Feel free to close this issue if your problem has been resolved.

**Comment by SLS8** [comment]
They're both black and white now. Thanks!!!

**Comment by dlemstra** [comment]
And sorry for taking this long, I completely forgot about this issue.....
