### ISSUE TITLE
Questions regarding Wand API

### ISSUE THREAD

**Issue by petersondrew** [dlemstra/GraphicsMagick.NET#4]
I'm just getting ramped up using GraphicsMagick.net and I was wondering what your gut feeling was on how difficult it would be to add support for a few of the Wand API functions. Specifically, I was considering implementing the AutoOrient function (which I think would be a useful method to expose on the MagickImage class).

There are a lot of gaps in my understanding of GraphicsMagick and this wrapper in particular, so I was wondering whether you thought that would be very difficult for a newcomer to tackle or not. Thanks!

**Comment by dlemstra** [comment]
I personally would like to switch to the implementation that I use in Magick.NET. This implementation uses an "old" method to call the GraphicsMagick library. My plan is to copy the Magick.NET source and strip out what is not available in GraphicsMagick. But I need a couple days off to make this possible.

**Comment by dlemstra** [comment]
Do you want me to leave this open @petersondrew or can we close it?

**Comment by petersondrew** [comment]
It can be closed, I went ahead and ported the auto orient code from the GM command line utility to my code because it ended up being very short and simple. Thanks for the follow-up.
