### ISSUE TITLE
Cannot implement custom font

### ISSUE THREAD

**Issue by tomling** [dlemstra/GraphicsMagick.NET#6]
Hi

I have a custom font in my Windows Font folder but when I try instantiate a new DrawableFont like so -
`drawables.Add(new DrawableFont("CustomFontName", FontStyleType.Any, FontWeight.Weight500, FontStretch.Normal));`

I get the following exception when calling `image.Draw(drawables)` - 

> GraphicsMagick.MagickTypeErrorException: 'ProjectName: Unable to read font (n019003l.pfb) reported by ..\..\magick\annotate.c:1063 (RenderFreetype)'

Is there something I am missing?

Thanks

**Comment by dlemstra** [comment]
Hve you tried specifying the full path to the pfb file?

**Comment by TomLing** [comment]
Hi - Thank you for your reply.

Yes I have tried specifying the absolute path to no avail. For example 

> C:\temp\fonts\CustomFont.pfb

**Comment by dlemstra** [comment]
Is it possible to share your custom font?
