### ISSUE TITLE
RGB image anti-aliasing - not able to override default behaviour

### ISSUE THREAD

**Issue by benbhall** [dlemstra/GraphicsMagick.NET#7]
Anti-aliasing is being aplied to RGB TIFF images regardless of setting property MagickImage.AntiAlias to false. Any tips?

Note also that it is an 8-bit image, which correctly identifies as such in the Depth property during debugging. However, on Write to file it becomes 16-bit; presumably to support the additional colours required for the anti-aliasing?

Confirmed in Debug output:

> 20180115100951 0:11 5.788 43112 tiff.c WriteTIFFImage 4904 Coder Event Image depth 8 bits

No mention of anti-aliasing in debug output.

Then when that TIFF is tested with 'gm identify':

```
  Depth: 16 bits-per-pixel component
  Channel Depths:
    Red:      16 bits
    Green:    16 bits
    Blue:     16 bits
```
Edit: Using ColorSpace.RGB

**Comment by dlemstra** [comment]
Do you have a small code sample that I can use to reproduce this issue?

**Comment by dlemstra** [comment]
@benbhall Can we close this issue?
