### ISSUE TITLE
Path with non-ASCII characters not supported

### ISSUE THREAD

**Issue by MarcCueni** [dlemstra/GraphicsMagick.NET#8]
[GraphicsMagick.MagickImage]::new(FilePath) returns an error when FilePath contains non-ascii characters, like accented characters (plenty in french). The error returned looks like: Exception calling ".ctor" with "1" argument(s): "PowerShell_ISE: Unable to open file (\\serverName\ShareName\FolderTree\accentués\filename.JPG) reported by ..\..\magick\blob.c:2838 (OpenBlob)"
There is no problem when using [ImageMagick.MagickImage]::new(SameFileName), but GraphicsMagick .Net seems so much quicker and treat EMF files better than ImageMagick (it get the dimensions of certains EMF with 1 to 2 pixels difference from what's reported by IrfanView for example),
Version of GraphicsMagick.Net is GraphicsMagick.NET-Q8-x64.1.3.26.1\lib\net40-client\GraphicsMagick.NET-x64.dll on Windows 10 Entreprise x64, v1703. I've tried older version, but this seems to be an old problem.
Many thanks if it can be fixed, and for making this available in the first place!
Best regards

**Comment by dlemstra** [comment]
GraphicsMagick does not support reading from paths with non-ASCII characters. I think this has been reported a couple years ago to the GraphicsMagick maintainer but I have no idea if support for that will be added any time soon.
