### ISSUE TITLE
Write method from ImageCollection returns "Value cannot be null. Parameter name: source"

### ISSUE THREAD

**Issue by jchurrocarvalho** [dlemstra/GraphicsMagick.NET#9]
Write method from ImageCollection returns "Value cannot be null. Parameter name: source".
I pretend to read several tiff multipage files and write all pages in one tiff multipage file. The code i use is only this:

        public static void TiffMergeImages(string[] vecFileNames, System.IO.Stream streamOut, GraphicsMagick.CompressionMethod compression, int quality = 0)
        {
            GraphicsMagick.MagickImageCollection    collImageMag = null;

            try
            {
                GraphicsMagick.MagickReadSettings   imageMagReadSettings;
                imageMagReadSettings = new GraphicsMagick.MagickReadSettings();
                imageMagReadSettings.SetDefine(GraphicsMagick.MagickFormat.Tiff, "ignore-tags", "32931,32934");

                collImageMag = new GraphicsMagick.MagickImageCollection();

                foreach ( string itFileName in vecFileNames )
                {
                    collImageMag.AddRange(itFileName, imageMagReadSettings);
                }

                foreach ( GraphicsMagick.MagickImage itImage in collImageMag )
                {
                    itImage.Format = GraphicsMagick.MagickFormat.Tiff;
                    //itImage.ColorSpace = ImageMagick.ColorSpace.sRGB;
                    //itImage.ColorType = ImageMagick.ColorType.Grayscale;
                    if ( quality > 0 )
                        itImage.Quality = quality;
                    itImage.CompressionMethod = compression;
                }

                collImageMag.Write(streamOut);
                collImageMag.Dispose();
                collImageMag = null;
            }
            catch
            {
                if ( collImageMag != null )
                    collImageMag.Dispose();
                throw;
            }
        }

the caller

GmagickHelper.TiffMergeImages(vecFiles, fsOut, GraphicsMagick.CompressionMethod.JPEG, 75);

Then i made debug and noticed that the lib throws the exception in
"MethodExtensions.cs" in line 70.

Bug? or something else?

**Comment by jchurrocarvalho** [comment]
I tried with compression.LZW and it worked. So the problem is related to compression.JPEG?

**Comment by dlemstra** [comment]
I have no idea where this exception is being thrown. Can you get more information from your stack trace?
